# Generated by Django 5.2.8 on 2025-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0002_trip_route_raw_trip_route_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hos_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
